site_name: Coucou! Let's collaborate.
site_url: https://www.coucal.org
theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo-48.png
  features:
    - content.code.copy

repo_url: https://github.com/coucouland/coucal-user-guide
repo_name: coucouland/coucal
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/coucouland
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/benfortuna
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/micronode
nav:
  - Overview:
    - Introduction: index.md
    - Features: features.md
    - Design: design.md
    - First Steps: first-steps.md
    - Examples:
        - Overview: examples/index.md
        - Scheduling: examples/schedule.md
  - Concepts:
    - Templates: templates.md
    - Collections: collections.md
    - Queries: queries.md
    - Connectors: connectors.md
    - Channels: channels.md
  - Scheduling: schedule.md
  - Tracker: tracker.md
  - Availability: availability.md
  - Journaling: journal.md
  - Assets: assets.md
  - Entities: entities.md
  - Attachments: attachments.md
